server:
  port: 3010
spring:
  application:
    name: XunYuan-User-CV-Server
  data:
    mongodb:
      database: xunyuan_user_cv_db
      uri: mongodb://localhost:27017
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
        group: XunYuan_Group
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher