server:
  port: 5010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xunyuan_company_db?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:/mappers/*.xml
