server:
  port: 5030

spring:
  application:
    name: XunYuan-User-Service
  datasource:
    url: jdbc:mysql://localhost:3306/xunyuan_user_db?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:11520
        username: nacos
        password: nacos
        group: XunYuan_Group
        namespace: public
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mappers/*.xml
