server:
  port: 11877

spring:
  application:
    name: XunYuan-SpringSecurity-GateWay-API
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  expiration: 1200
  secretSalt: tocchen.top@XunYuan
  tokenHead: Bearer  #JWT负载中拿到开头
  tokenHeader: Authorization #JWT存储的请求头