server:
  port: 2010
spring:
  application:
    name: XunYuan-Data-CV-Server
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/xunyuan_cv_db?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
        group: XunYuan_Group
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:/mappers/*.xml