server:
  port: 5010
spring:
  application:
    name: XunYuan-ManagerSystem-Company-Service
  datasource:
    url: jdbc:mysql://localhost:3306/xunyuan_company_db?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    password: 123456
    database: 1
    timeout: 2000ms
  cache:
    type: redis

  cloud:
    nacos:
      discovery:
        server-addr: localhost:11520
        username: nacos
        password: nacos
        namespace: public
        group: XunYuan_Group
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:/mappers/*.xml
