server:
  port: 5011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xunyuan_manager_db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mappers/*.xml
