server:
  port: 1010

spring:
  application:
    name: XunYuan-Security-GateWay-Service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: localhost:11520
        username: nacos
        password: nacos
        group: XunYuan_Group
        namespace: public
  main:
    allow-bean-definition-overriding: true
jwt:
  expiration: 1200
  secretSalt: tocchen.top@XunYuan
  tokenHead: Bearer  #JWT负载中拿到开头
  tokenHeader: Authorization #JWT存储的请求头